In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
from sklearn.datasets import load_boston

In [3]:
bd=load_boston()
df=pd.DataFrame(bd.data,columns=bd.feature_names)
df.head(3)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03

In [74]:
X=df
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [82]:
y=bd.target.reshape(-1,1)
y[0:5:1]

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2]])

In [51]:
from sklearn.linear_model import LinearRegression

In [52]:
from sklearn.metrics import mean_squared_error

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size = 0.2,random_state=0)

In [55]:
regressor= LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [85]:
y_train[0:5:1]

array([[26.7],
       [21.7],
       [22. ],
       [22.9],
       [10.4]])

In [86]:
y_pred_train=regressor.predict(X_train)
y_pred_train[0:5:1]

array([[32.55692655],
       [21.92709478],
       [27.54382573],
       [23.60318829],
       [ 6.57190962]])

In [87]:
y_test[0:5:1]

array([[22.6],
       [50. ],
       [23. ],
       [ 8.3],
       [21.2]])

In [88]:
y_pred_test=regressor.predict(X_test)
y_pred_test[0:5:1]

array([[24.88963777],
       [23.72141085],
       [29.36499868],
       [12.12238621],
       [21.44382254]])

In [89]:
mse=mean_squared_error(y_train,y_pred_train)
mse

19.326470203585725

In [90]:
mse1=mean_squared_error(y_test,y_pred_test)
mse1

33.44897999767653

In [91]:
regressor.intercept_

array([38.09169493])

In [92]:
regressor.score(X,y)

0.7373440319905034

In [93]:
regressor.score(X_train,y_train)

0.7730135569264234

In [94]:
regressor.score(X_test,y_test)

0.5892223849182507